spring:
  application:
    name: gateway
  config:
    import: configserver:http://localhost:8888
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/user/**
            - id: study-service
              uri: lb://study-service
              predicates:
                - Path=/study/**
            - id: comment-service
              uri: lb://comment-service
              predicates:
                - Path=/comment/**, /notice/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
